// !!!!!!!  for Trilogy marketing video  !!!!!!!
// !!!!!!!          to be deleted        !!!!!!!
import 'dart:math';
import '../../../../Server/src/database_helper.dart';

final List<graphData> rowData = [
      // graphData(
      //   timestamp: '2023-06-08 12:00:00',
      //   batteryText: '38%',
      //   heartRateText: '77 bpm',
      //   spo2Text: '98%',
      //   glucose_mmolL: 2.0 + Random().nextDouble() * 11,
      //   glucose_mgDL: .01,
      //   cholesterolText: '2.01 mg/dL',
      //   UA_menText: 'Normal: 0.32 mmol/L',
      //   UA_womenText: 'Normal: 0.26 mmol/L',
      // ),
      graphData(
        timestamp: '2023-06-26 12:00:00',
        batteryText: '38%',
        heartRateText: '77 bpm',
        spo2Text: '98%',
        glucose_mmolL: 2.0 + Random().nextDouble() * 11,
        glucose_mgDL: .01,
        cholesterolText: '2.01 mg/dL',
        UA_menText: 'Normal: 0.32 mmol/L',
        UA_womenText: 'Normal: 0.26 mmol/L',
      ),
      graphData(
        timestamp: '2023-06-26 18:00:00',
        batteryText: '38%',
        heartRateText: '77 bpm',
        spo2Text: '98%',
        glucose_mmolL: 2.0 + Random().nextDouble() * 11,
        glucose_mgDL: .01,
        cholesterolText: '2.01 mg/dL',
        UA_menText: 'Normal: 0.32 mmol/L',
        UA_womenText: 'Normal: 0.26 mmol/L',
      ),
      graphData(
        timestamp: '2023-06-28 18:00:00',
        batteryText: '38%',
        heartRateText: '77 bpm',
        spo2Text: '98%',
        glucose_mmolL: 2.0 + Random().nextDouble() * 11,
        glucose_mgDL: .01,
        cholesterolText: '2.01 mg/dL',
        UA_menText: 'Normal: 0.32 mmol/L',
        UA_womenText: 'Normal: 0.26 mmol/L',
      ),
      graphData(
        timestamp: '2023-06-30 18:00:00',
        batteryText: '38%',
        heartRateText: '77 bpm',
        spo2Text: '98%',
        glucose_mmolL: 2.0 + Random().nextDouble() * 11,
        glucose_mgDL: .01,
        cholesterolText: '2.01 mg/dL',
        UA_menText: 'Normal: 0.32 mmol/L',
        UA_womenText: 'Normal: 0.26 mmol/L',
      ),
      graphData(
        timestamp: '2023-06-30 18:00:00',
        batteryText: '38%',
        heartRateText: '77 bpm',
        spo2Text: '98%',
        glucose_mmolL: 2.0 + Random().nextDouble() * 11,
        glucose_mgDL: .01,
        cholesterolText: '2.01 mg/dL',
        UA_menText: 'Normal: 0.32 mmol/L',
        UA_womenText: 'Normal: 0.26 mmol/L',
      ),
      graphData(
        timestamp: '2023-07-01 12:00:00',
        batteryText: '38%',
        heartRateText: '77 bpm',
        spo2Text: '98%',
        glucose_mmolL: 2.0 + Random().nextDouble() * 11,
        glucose_mgDL: .01,
        cholesterolText: '2.01 mg/dL',
        UA_menText: 'Normal: 0.32 mmol/L',
        UA_womenText: 'Normal: 0.26 mmol/L',
      ),
      graphData(
        timestamp: '2023-07-01 19:00:00',
        batteryText: '38%',
        heartRateText: '77 bpm',
        spo2Text: '98%',
        glucose_mmolL: 2.0 + Random().nextDouble() * 11,
        glucose_mgDL: .01,
        cholesterolText: '2.01 mg/dL',
        UA_menText: 'Normal: 0.32 mmol/L',
        UA_womenText: 'Normal: 0.26 mmol/L',
      ),
      graphData(
        timestamp: '2023-07-22 19:00:00',
        batteryText: '38%',
        heartRateText: '77 bpm',
        spo2Text: '98%',
        glucose_mmolL: 2.0 + Random().nextDouble() * 11,
        glucose_mgDL: .01,
        cholesterolText: '2.01 mg/dL',
        UA_menText: 'Normal: 0.32 mmol/L',
        UA_womenText: 'Normal: 0.26 mmol/L',
      ),
      graphData(
        timestamp: '2023-07-23 19:00:00',
        batteryText: '38%',
        heartRateText: '77 bpm',
        spo2Text: '98%',
        glucose_mmolL: 2.0 + Random().nextDouble() * 11,
        glucose_mgDL: .01,
        cholesterolText: '2.01 mg/dL',
        UA_menText: 'Normal: 0.32 mmol/L',
        UA_womenText: 'Normal: 0.26 mmol/L',
      ),
      graphData(
        timestamp: '2023-07-25 19:00:00',
        batteryText: '38%',
        heartRateText: '77 bpm',
        spo2Text: '98%',
        glucose_mmolL: 2.0 + Random().nextDouble() * 11,
        glucose_mgDL: .01,
        cholesterolText: '2.01 mg/dL',
        UA_menText: 'Normal: 0.32 mmol/L',
        UA_womenText: 'Normal: 0.26 mmol/L',
      ),
      graphData(
        timestamp: '2024-07-25 19:00:00',
        batteryText: '38%',
        heartRateText: '77 bpm',
        spo2Text: '98%',
        glucose_mmolL: 2.0 + Random().nextDouble() * 11,
        glucose_mgDL: .01,
        cholesterolText: '2.01 mg/dL',
        UA_menText: 'Normal: 0.32 mmol/L',
        UA_womenText: 'Normal: 0.26 mmol/L',
      ),
      graphData(
        timestamp: '2024-07-25 19:00:00',
        batteryText: '38%',
        heartRateText: '77 bpm',
        spo2Text: '98%',
        glucose_mmolL: 2.0 + Random().nextDouble() * 11,
        glucose_mgDL: .01,
        cholesterolText: '2.01 mg/dL',
        UA_menText: 'Normal: 0.32 mmol/L',
        UA_womenText: 'Normal: 0.26 mmol/L',
      ),
      graphData(
        timestamp: '2024-07-27 19:00:00',
        batteryText: '38%',
        heartRateText: '77 bpm',
        spo2Text: '98%',
        glucose_mmolL: 2.0 + Random().nextDouble() * 11,
        glucose_mgDL: .01,
        cholesterolText: '2.01 mg/dL',
        UA_menText: 'Normal: 0.32 mmol/L',
        UA_womenText: 'Normal: 0.26 mmol/L',
      ),
      graphData(
        timestamp: '2024-08-13 19:00:00',
        batteryText: '38%',
        heartRateText: '77 bpm',
        spo2Text: '98%',
        glucose_mmolL: 2.0 + Random().nextDouble() * 11,
        glucose_mgDL: .01,
        cholesterolText: '2.01 mg/dL',
        UA_menText: 'Normal: 0.32 mmol/L',
        UA_womenText: 'Normal: 0.26 mmol/L',
      ),
      graphData(
        timestamp: '2025-02-28 19:00:00',
        batteryText: '38%',
        heartRateText: '77 bpm',
        spo2Text: '98%',
        glucose_mmolL: 2.0 + Random().nextDouble() * 11,
        glucose_mgDL: .01,
        cholesterolText: '2.01 mg/dL',
        UA_menText: 'Normal: 0.32 mmol/L',
        UA_womenText: 'Normal: 0.26 mmol/L',
      ),
      graphData(
        timestamp: '2025-03-13 19:00:00',
        batteryText: '38%',
        heartRateText: '77 bpm',
        spo2Text: '98%',
        glucose_mmolL: 2.0 + Random().nextDouble() * 11,
        glucose_mgDL: .01,
        cholesterolText: '2.01 mg/dL',
        UA_menText: 'Normal: 0.32 mmol/L',
        UA_womenText: 'Normal: 0.26 mmol/L',
      ),
    ];